BASE_DOWNLOAD_PATH <- "~/Downloads/CovidData"

# CONSTANTS
HOSPITALISATIONS_CSV_URL <- "https://epistat.sciensano.be/Data/COVID19BE_HOSP.csv"
HOSPITALISATIONS_CSV_FILE_PATH <- paste(BASE_DOWNLOAD_PATH,"COVID19BE_HOSP.csv",sep="/")

MORTALITY_CSV_URL <- "https://epistat.sciensano.be/Data/COVID19BE_MORT.csv"
MORTALITY_CSV_FILE_PATH <- paste(BASE_DOWNLOAD_PATH,"/COVID19BE_MORT.csv",sep="/")

CASES_CSV_URL <- "https://epistat.sciensano.be/Data/COVID19BE_CASES_AGESEX.csv"
CASES_CSV_FILE_PATH <- paste(BASE_DOWNLOAD_PATH,"/COVID19BE_CASES.csv",sep="/")